# Problem 2 - Even Fibonacci numbers
#   Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#   By starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#   By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#   find the sum of the even-valued terms.


def solution():
    prev2 = [1, 2]
    s = 2
    while True:
        n = prev2[0] + prev2[1]
        if n > 4000000:
            break
        prev2[0] = prev2[1]
        prev2[1] = n
        if n % 2 == 0:
            s += n
    return s

if __name__ == '__main__':
    print solution()
